version: "3.8"
services:
  app:
    build: .
    ports:
      - "5174:5173"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
